Add dockerfile for the docker images templates Add makeclass script to provisoiner the environment Add the puppet-dns module

diff --git a/tools/install_tools b/tools/install_tools
--- a/tools/install_tools
+++ b/tools/install_tools
@@ -46,4 +46,8 @@ echo "
 fiap ALL=(ALL:ALL) NOPASSWD: ALL
 " >> /etc/sudoers.d/fiap
 
-
+echo "Installing the makeclass tools"
+if ! cp /vagrant/tools/makeclass /bin/makeclass; then
+	echo "Could not install the makeclass tool for class automation"
+	exit 1
+fi
